#spring.application.name=filmorate
spring.output.ansi.enabled=always
#logging.level.root=INFO
#logging.level.org.springframework=DEBUG
#logging.level.com.yourpackage=DEBUG

spring.datasource.url=jdbc:h2:file:./database/filmorate_db;AUTO_SERVER=TRUE
spring.sql.init.mode=always
spring.datasource.username=username
spring.datasource.password=password
spring.datasource.driver-class-name=org.h2.Driver


